### PR TITLE
remove odd numbered key:value on debugs

### PR DESCRIPTION
**Pull request by enderv**
Signed-off-by: cvodak1 <cvodak@ea.com>

### Description of your changes
Fixes # https://github.com/crossplane/crossplane-runtime/issues/247

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Unit tests run only

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by hasheddan** [comment]
Ah thanks @enderv! Wasn't aware you were tackling this, I'll close #248 in favor of this one :)

**Review by hasheddan — APPROVED** [review]

**Comment by negz** [comment]
@hasheddan @enderv What do you think about passing a debug logger to the unit tests to catch this?

**Comment by hasheddan** [comment]
@negz I tried that out, but wasn't sure if we wanted actual debug logs in test output. That being said, it might actually be nice to see those and they would only show up on test failures I believe.

@enderv you should be able to add this by adding a `WithLogger(logging.NewLogrLogger(zap.New(zap.UseDevMode(true))))` reconciler option to the various tests in the table.

**Comment by enderv** [comment]
@hasheddan  yeah sorry was feeling ambitious and they said it was just one line change, didn't know you saw it as well. 

trying the logger bit now

**Comment by enderv** [comment]
@hasheddan @negz added. Verified locally that they fail by rebreaking the debug log.

**Comment by hasheddan** [comment]
Hmm looks like this does dump the debug logs into stdout on successful runs too. Mind dropping the second commit for the time-being @enderv and we can evaluate how we want to handle this across all the projects?

**Comment by enderv** [comment]
@hasheddan sounds good. removed it for now

**Pull request merged**
