### PR TITLE
renovate: configuration

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Configure renovate, configuration similar to crossplane's one. Not targeting release branches on purpose.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Configured on my fork.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by turkenh — APPROVED** [review]

**Comment by turkenh** [comment]
@phisco looks like we also have dependabot configured: https://github.com/crossplane/crossplane-runtime/pulls/app%2Fdependabot

AFAIR, we have agreed on converging on renovate, should we disable dependabot in this case?

**Comment by phisco** [comment]
Take care not to disable dependabot security alerts though.

**Comment by turkenh** [comment]
Ok, disabled `Dependabot security updates` and `Dependabot version updates` was already disabled since both will be covered by `renovate`. Can you confirm?

**Comment by phisco** [comment]
Perfect, thanks! 👍

**Pull request merged**
