### PR TITLE
[Backport release-0.19] Max index value validation

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes
Backport of #389 and GHSA-vfvj-3m3g-m532.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenh** [comment]
@phisco can you cherry pick with `-x`:

```
       -x
           When recording the commit, append a line that says "(cherry picked from commit ...)" to the original
           commit message in order to indicate which commit this change was cherry-picked from. This is done only for
           cherry picks without conflicts. Do not use this option if you are cherry-picking from your private branch
           because the information is useless to the recipient. If on the other hand you are cherry-picking between
           two publicly visible branches (e.g. backporting a fix to a maintenance branch for an older release from a
           development branch), adding this information can be useful.
```

**Review by turkenh — APPROVED** [review]

**Comment by jbw976** [comment]
@phisco Is there a reason that we couldn't/didn't use the backport bot to make this backport PR? 🤔

**Comment by phisco** [comment]
Would probably make sense to add the backport labels checkbox to the issue template as we are already doing for Crossplane. Wdyt @jbw976?

**Comment by jbw976** [comment]
that would sound reasonable to me 😇

**Pull request merged**
