### PR TITLE
Update controller-runtime to v0.13.0

### PR DESCRIPTION
**Pull request by saschagrunert**
### Description of your changes

This also bumps related dependencies and adapts required code paths.

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by negz** [comment]
I'm a +1 on prioritizing this, especially because client-go v0.25.0 will bring in a bunch of client-side performance improvements for clusters operating with a lot of API groups (i.e. CRDs).

**Review by negz — APPROVED** [review]

**Comment by negz** [comment]
@saschagrunert Before I merge, can you elaborate on how (or if) you've tested this?

**Comment by saschagrunert** [comment]
> @saschagrunert Before I merge, can you elaborate on how (or if) you've tested this?

I just verified it via the CI, no additional manual tests have been done on my side.

**Comment by negz** [comment]
> I just verified it via the CI, no further manual tests have been done on my side.

We typically like to at least build crossplane/crossplane against the updated deps (e.g. using a replace in the go.mod to point runtime at your branch) and make sure it seems to run. Would you be able to do that? I know you use runtime in a different project than us.

**Pull request closed without merging**
