### PR TITLE
Remove golangci-lint config

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

See https://github.com/crossplane/crossplane/issues/1283 for context

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [ ] Updated any relevant [documentation], [examples], or [release notes].
- [ ] Updated the RBAC permissions in [`clusterrole.yaml`] to include any new types.

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[release notes]: https://github.com/crossplane/crossplane/tree/master/PendingReleaseNotes.md
[`clusterrole.yaml`]: https://github.com/crossplane/crossplane/blob/master/cluster/charts/crossplane/templates/clusterrole.yaml

### CODE REVIEW

**Comment by negz** [comment]
> does this mean that builds will pass when linter errors occur, but bot will comment?

No, builds will fail. Jenkins and https://golangci.com both invoke golangci-lint, and will both fail the build if there's a linter error. So https://golangci.com is a little redundant, but reports linter issues more clearly and in some cases makes suggestions on how to fix them.

**Comment by hasheddan** [comment]
@negz thanks for clarifying that! Any idea what’s happening with CI here?

**Comment by negz** [comment]
> Any idea what’s happening with CI here?

Yeah - I forgot to store the API token required to upload the report as a Jenkins credential. This is now fixed!

**Comment by hasheddan** [comment]
@negz I believe you can hit merge on this one :+1:

**Pull request merged**
