### PR TITLE
chore(renovate): group also actions' digest

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Groups GitHub Actions' digests updates together with minor and patches.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

`renovate-config-validator` approved the formatting, no need to test the functionality on my fork.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenh** [comment]
@phisco could you shed some light on the reasoning behind this PR, e.g. what will change after this and why?

**Comment by phisco** [comment]
@turkenh @jbw976 brought to my attention that digest PRs were a bit noisy [here](https://github.com/crossplane/crossplane-runtime/pull/420#discussion_r1155150495), so I checked and noticed we forgot to group digest bumps with the rest of the non-major upgrades to github actions

**Comment by turkenh** [comment]
Thanks @phisco. So would this mean "less frequent bumps" at the end?

**Comment by phisco** [comment]
Less PRs, as all the following PRs here would be grouped in a single one: #420 #419 #421 #424 . If we still find it to bee too noisy we can add a filter to have digests only bumped every two weeks as we are doing for docker images.

**Review by turkenh — APPROVED** [review]

**Pull request merged**
